### ISSUE TITLE
ECONOMY API NUKKIT 버전 오류

### ISSUE THREAD

**Issue by KIKIIIRI** [onebone/EconomyS#355]
13:55:23 [INFO] EconomyAPI v1.0.0 로드 중
> Exception in thread "main" java.lang.NoClassDefFoundError: cn/nukkit/event/TextContainer
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:53)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:384)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.ClassNotFoundException: cn.nukkit.event.TextContainer
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
계속 이렇게 뜹니다
플긴은
GetClientId v1.0.0 로드 중
 AdminJQ v0.0.1 로드 중
 chatclear v1.0.0 로드 중
 ChildWebInfo v1.0 로드 중
ColorOpChat v1.0.0 로드 중
ColorOpName v1.0.0 로드 중
 CommandLog v1.0.0 로드 중
 Coupon v1.0.0 로드 중
이정도 장착한 상태고요
NUKKIT이라서 오류로그같은게 없네요

**Comment by onebone** [comment]
최신 버전이 아닙니다.

https://jenkins.onebone.me/job/EconomyAPI 에서 다운로드 받아주세요.
